# For more information: https://laravel.com/docs/sail
version: '3'
services:
    api:
        image: todo_api
        container_name: todo_api
        build: 
          context: ./backend
          dockerfile: Dockerfile
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www/html'
        # networks:
        #     - sail
        # depends_on:
        #     - pgsql

