version: "3.8"
services:
  # backend
  app:
    image: todo_api
    container_name: todo_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/var/www/html"
    networks:
      - todo_network
    depends_on:
      - pgsql

  # database
  pgsql:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - todo_network

  # db manager
  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - todo_pgadmin:/var/lib/pgadmin
    networks:
      - todo_network

  # db manager
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8282:8080"
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  todo_rds:
    driver: local
  todo_pgadmin:
    driver: local