# For more information: https://laravel.com/docs/sail
version: "3"
services:
  api:
    image: todo_api
    container_name: todo_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./backend:/var/www/html"
    networks:
      - todo_network
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    container_name: todo_rds
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    volumes:
      - todo_rds:/var/lib/postgresql/data
    networks:
      - todo_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: todo123
    volumes:
      - todo_pgadmin:/var/lib/pgadmin
    networks:
      - todo_network

networks:
    todo_network:
      driver: bridge

volumes:
  todo_rds:
      driver: local
  todo_pgadmin:
      driver: local
