version: "3.8"
services:
  api:
    image: todo_api
    container_name: todo_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/var/www/html"
    networks:
      - todo_network
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    container_name: todo_rds
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    volumes:
      - todo_rds:/var/lib/postgresql/data
    networks:
      - todo_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8282:8080"
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  todo_rds:
    driver: local
  todo_pgadmin:
    driver: local
